apiVersion: v1
kind: Namespace
metadata:
  name: openfaas

---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas-fn

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfaas-controller
  namespace: openfaas

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: openfaas
  labels:
    app: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ghcr.io/openfaas/gateway:0.27.12
          ports:
            - containerPort: 8080
            - containerPort: 8085
          env:
            - name: read_timeout
              value: "1m05s"
            - name: write_timeout
              value: "1m05s"
            - name: upstream_timeout
              value: "1m"
            - name: functions_provider_url
              value: "http://127.0.0.1:8080/"
            - name: async
              value: "true"
            - name: faas_nats_address
              value: "nats.openfaas.svc.cluster.local"
            - name: faas_nats_port
              value: "4222"
            - name: basic_auth
              value: "false"
            - name: faas_nats_cluster_id
              value: "faas-cluster"

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: openfaas
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.25.6
          ports:
            - containerPort: 4222
            - containerPort: 6222
          args:
            - "-p"
            - "4222"
            - "-m"
            - "8222"
            - "-hbi"
            - "5s"
            - "-hbt"
            - "5s"
            - "-hbf"
            - "2"
            - "-cid"
            - "faas-cluster"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: openfaas
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: gateway

---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: openfaas
spec:
  type: ClusterIP
  ports:
    - port: 4222
      targetPort: 4222
      protocol: TCP
      name: client
    - port: 8222
      targetPort: 8222
      protocol: TCP
      name: cluster
  selector:
    app: nats
